name: Build and Release Python Binary

on:
  push:
    tags:
      - "v*"  # Trigger only on tag pushes with version-like names

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Replace with your Python version

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      # Step 4: Build the binary
      - name: Build Binary
        run: |
          pyinstaller --clean --onefile --version-file="version.rc" --console copier.py

      # Step 5: Upload the binary as a release asset
      - name: Upload Binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/copier.exe  # Path to the binary
          asset_name: copier.exe  # Name of the binary file
          asset_content_type: application/octet-stream

  create_release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: "Automated release of version ${{ github.ref_name }}"
          draft: false
          prerelease: false
